import type { Metadata } from 'next'

export const metadata: Metadata = { title: 'The ecosystem', description: 'How Front Page Intelligence, Operators Academy, Front Page Agency, and private coaching fit together.' }

export default function Page() {
  return (
    <main><section className="band mint"><div className="wrap"><a className="backlink" href="/guides">← All free guides</a><span className="eyebrow">The ecosystem</span><h1>{"Learn it. Build it. "}<em>Put it to work.</em></h1><p className="lead">Technology, operator development, and focused support for your business. Here is how the pieces fit.</p></div></section><section className="wrap eco"><article className="lead-card"><small>Technology</small><h2>Front Page Intelligence</h2><p>The technology layer: bringing AI and business systems into the way a company operates. This is the primary product direction behind Aton’s work, built inside our own operations first.</p><a className="button light" href="/contact?topic=intelligence">Ask about Front Page Intelligence</a></article><article><small>Community</small><h2>Operators Academy</h2><p>The free community for developing operators, with an in-person operation planned as its next stage.</p><a className="button" href="https://www.skool.com/operators-academy-5634">Join the free community</a></article><article><small>Operating experience</small><h2>Front Page Agency</h2><p>The sales organization behind the sales, team-development and leadership lessons shared here. The lessons get tested there first.</p></article><article><small>Private coaching and consulting</small><h2>Work with Aton</h2><p>Focused support through online strategy sessions and fly-in one-on-one engagements. Applications are reviewed before anything is booked, and scope and deposit terms are shown in writing first.</p><a className="button secondary" href="/contact?topic=coaching">Apply for private coaching</a></article><article><small>Free guides</small><h2>Start here</h2><p>Every guide is a full lesson, a tool you can use the same day, and one clear next step.</p><a className="button secondary" href="/guides">Browse the library</a></article></section></main>
  )
}
